<?php
defined("ABSPATH") or die();

if (function_exists("acf_add_local_field_group")):
	acf_add_local_field_group([
		"key" => "group_5d22d2f0f0943",
		"title" => "Email Settings",
		"fields" => [
			[
				"key" => "field_5d22d60c98e15",
				"label" => "Lost Password",
				"name" => "",
				"type" => "tab",
				"instructions" => "",
				"required" => 0,
				"conditional_logic" => 0,
				"wrapper" => [
					"width" => "",
					"class" => "",
					"id" => "",
				],
				"placement" => "left",
				"endpoint" => 0,
			],
			[
				"key" => "field_5d22d7610c141",
				"label" => "Note:",
				"name" => "",
				"type" => "message",
				"instructions" => "",
				"required" => 0,
				"conditional_logic" => 0,
				"wrapper" => [
					"width" => "",
					"class" => "",
					"id" => "",
				],
				"message" => 'Placeholders:
<b>{site_url}</b> | <b>{first_name}</b> | <b>{last_name}</b> | <b>{full_name}</b> | <b>{user_email}</b> | <b>{reset_password_url}</b>',
				"new_lines" => "wpautop",
				"esc_html" => 0,
			],
			[
				"key" => "field_5d22d62398e16",
				"label" => "Subject",
				"name" => "bd_lost_password_subject",
				"type" => "text",
				"instructions" => "",
				"required" => 0,
				"conditional_logic" => 0,
				"wrapper" => [
					"width" => "",
					"class" => "",
					"id" => "",
				],
				"default_value" => "Reset Password Notification",
				"placeholder" => "",
				"prepend" => "",
				"append" => "",
				"maxlength" => "",
			],
			[
				"key" => "field_5d22d62d98e17",
				"label" => "Body",
				"name" => "bd_lost_password_body",
				"type" => "wysiwyg",
				"instructions" => "",
				"required" => 0,
				"conditional_logic" => 0,
				"wrapper" => [
					"width" => "",
					"class" => "",
					"id" => "",
				],
				"default_value" => 'Hi, click here to reset your password

{reset_password_url}',
				"tabs" => "all",
				"toolbar" => "full",
				"media_upload" => 1,
				"delay" => 0,
			],
			[
				"key" => "field_5d22d60c98e16",
				"label" => "Create Team",
				"name" => "",
				"type" => "tab",
				"instructions" => "",
				"required" => 0,
				"conditional_logic" => 0,
				"wrapper" => [
					"width" => "",
					"class" => "",
					"id" => "",
				],
				"placement" => "left",
				"endpoint" => 0,
			],
			[
				"key" => "field_5d22d7610c142",
				"label" => "Note:",
				"name" => "",
				"type" => "message",
				"instructions" => "",
				"required" => 0,
				"conditional_logic" => 0,
				"wrapper" => [
					"width" => "",
					"class" => "",
					"id" => "",
				],
				"message" => 'Placeholders:
<b>{team_name}</b> | <b>{team_code}</b> | <b>{team_unique_link}</b>',
				"new_lines" => "wpautop",
				"esc_html" => 0,
			],
			[
				"key" => "field_5d22d62398e17",
				"label" => "Subject",
				"name" => "bd_create_team_subject",
				"type" => "text",
				"instructions" => "",
				"required" => 0,
				"conditional_logic" => 0,
				"wrapper" => [
					"width" => "",
					"class" => "",
					"id" => "",
				],
				"default_value" => "Create Team",
				"placeholder" => "",
				"prepend" => "",
				"append" => "",
				"maxlength" => "",
			],
			[
				"key" => "field_5d22d62d98e18",
				"label" => "Body",
				"name" => "bd_create_team_body",
				"type" => "wysiwyg",
				"instructions" => "",
				"required" => 0,
				"conditional_logic" => 0,
				"wrapper" => [
					"width" => "",
					"class" => "",
					"id" => "",
				],
				"default_value" => "Hi, you have created a new team, {team_name}, {team_code}, {team_unique_link}",
				"tabs" => "all",
				"toolbar" => "full",
				"media_upload" => 1,
				"delay" => 0,
			],
			[
				"key" => "field_5d22d60c98e17",
				"label" => "Resend Team Code",
				"name" => "",
				"type" => "tab",
				"instructions" => "",
				"required" => 0,
				"conditional_logic" => 0,
				"wrapper" => [
					"width" => "",
					"class" => "",
					"id" => "",
				],
				"placement" => "left",
				"endpoint" => 0,
			],
			[
				"key" => "field_5d22d7610c143",
				"label" => "Note:",
				"name" => "",
				"type" => "message",
				"instructions" => "",
				"required" => 0,
				"conditional_logic" => 0,
				"wrapper" => [
					"width" => "",
					"class" => "",
					"id" => "",
				],
				"message" => 'Placeholders:
<b>{team_name}</b> | <b>{team_code}</b> | <b>{team_unique_link}</b>',
				"new_lines" => "wpautop",
				"esc_html" => 0,
			],
			[
				"key" => "field_5d22d62398e19",
				"label" => "Subject",
				"name" => "bd_resend_team_code_subject",
				"type" => "text",
				"instructions" => "",
				"required" => 0,
				"conditional_logic" => 0,
				"wrapper" => [
					"width" => "",
					"class" => "",
					"id" => "",
				],
				"default_value" => "Team Code",
				"placeholder" => "",
				"prepend" => "",
				"append" => "",
				"maxlength" => "",
			],
			[
				"key" => "field_5d22d62d98e20",
				"label" => "Body",
				"name" => "bd_resend_team_code_body",
				"type" => "wysiwyg",
				"instructions" => "",
				"required" => 0,
				"conditional_logic" => 0,
				"wrapper" => [
					"width" => "",
					"class" => "",
					"id" => "",
				],
				"default_value" => "Hi, here is your team code, {team_name}, {team_code}, {team_unique_link}",
				"tabs" => "all",
				"toolbar" => "full",
				"media_upload" => 1,
				"delay" => 0,
			],
		],
		"location" => [
			[
				[
					"param" => "options_page",
					"operator" => "==",
					"value" => "email-settings",
				],
			],
		],
		"menu_order" => 0,
		"position" => "normal",
		"style" => "default",
		"label_placement" => "top",
		"instruction_placement" => "label",
		"hide_on_screen" => "",
		"active" => true,
		"description" => "",
	]);
endif;
